baseURL = "https://a-suricata.io/"
languageCode = "en-us"
title = "A Suricata"
theme = "hugo-notepadium"

[params]
logo = "meericon.png"
slogan = "Computation in Nature"

[params.comments]
enable = true

[params.math]
enable = true
use = "katex"

[[params.nav.custom]]
title = "About"
url = "/about"

[[params.nav.custom]]
title = "Blog"
url = "/blog"

[[params.nav.custom]]
title = "Github"
url = "https://github.com/cowkami/"
